-- Operator-owned rules replace executable PHP callbacks. Runtime credentials
-- can read a scoped snapshot and record only effects allowed by that snapshot.
CREATE SCHEMA admission;
REVOKE ALL ON SCHEMA admission FROM PUBLIC;
CREATE TABLE admission.policy (
    singleton boolean PRIMARY KEY DEFAULT true CHECK(singleton),
    revision bigint NOT NULL DEFAULT 1 CHECK(revision>0)
);
INSERT INTO admission.policy DEFAULT VALUES;
CREATE TABLE admission.capacity (
    singleton boolean PRIMARY KEY DEFAULT true CHECK(singleton),
    hit_limit integer NOT NULL DEFAULT 100000 CHECK(hit_limit BETWEEN 1 AND 1000000),
    log_limit integer NOT NULL DEFAULT 100000 CHECK(log_limit BETWEEN 1 AND 1000000),
    ban_limit integer NOT NULL DEFAULT 100000 CHECK(ban_limit BETWEEN 1 AND 1000000)
);
INSERT INTO admission.capacity DEFAULT VALUES;
CREATE TABLE admission.rules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK(id>0),
    position integer NOT NULL DEFAULT 0,
    active boolean NOT NULL DEFAULT true,
    board text NOT NULL DEFAULT '' CHECK(board='' OR board ~ '^[a-z0-9]{1,10}$'),
    pattern text NOT NULL CHECK(octet_length(pattern)<=2048),
    regex boolean NOT NULL DEFAULT false,
    autosage boolean NOT NULL DEFAULT false,
    log boolean NOT NULL DEFAULT false,
    quiet boolean NOT NULL DEFAULT false,
    lenient boolean NOT NULL DEFAULT false,
    ops_only boolean NOT NULL DEFAULT false,
    min_count integer NOT NULL DEFAULT 1 CHECK(min_count<=1024),
    ban_days integer NOT NULL DEFAULT 0 CHECK(ban_days BETWEEN -1 AND 3650),
    CHECK(regex OR pattern<>'' OR min_count<=1)
);
CREATE INDEX admission_rules_scope ON admission.rules(board,position,id) WHERE active;
CREATE FUNCTION admission.changed() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,pg_temp AS $$
BEGIN
    UPDATE admission.policy SET revision=revision+1 WHERE singleton;
    IF NOT FOUND THEN RAISE EXCEPTION 'Content admission policy is unavailable.' USING ERRCODE='55000'; END IF;
    RETURN NULL;
END $$;
CREATE TRIGGER admission_rules_changed AFTER INSERT OR UPDATE OR DELETE OR TRUNCATE ON admission.rules
    FOR EACH STATEMENT EXECUTE FUNCTION admission.changed();
-- Hits use the source's rolling one-hour duplicate boundary, including across
-- boards. IPv6 remains a distinct exact peer rather than collapsing to ip2long 0.
CREATE TABLE admission.hits (
    rule_id bigint NOT NULL, peer inet NOT NULL, board text NOT NULL,
    last_hit timestamptz NOT NULL, count bigint NOT NULL CHECK(count>0),
    PRIMARY KEY(rule_id,peer)
);
CREATE TABLE admission.logs (
    id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    rule_id bigint NOT NULL, board text NOT NULL, parent bigint NOT NULL CHECK(parent>=0),
    peer inet NOT NULL, created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    name text NOT NULL CHECK(octet_length(name)<=2048),
    subject text NOT NULL CHECK(octet_length(subject)<=2048),
    comment text NOT NULL CHECK(octet_length(comment)<=131072),
    filename text NOT NULL CHECK(octet_length(filename)<=1024)
);
CREATE TABLE admission.bans (
    peer inet PRIMARY KEY, board text NOT NULL, rule_id bigint,
    reason text NOT NULL CHECK(reason IN ('content','filename')),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    expires_at timestamptz, active boolean NOT NULL DEFAULT true
);
GRANT USAGE ON SCHEMA content,admission TO board_admission_owner;
GRANT SELECT(slug,staff_only) ON content.boards TO board_admission_owner;
GRANT SELECT ON admission.rules,admission.policy TO board_admission_owner;
GRANT UPDATE(singleton) ON admission.policy TO board_admission_owner;
GRANT SELECT,UPDATE ON admission.capacity TO board_admission_owner;
GRANT SELECT,INSERT,UPDATE ON admission.hits,admission.bans TO board_admission_owner;
GRANT SELECT,INSERT ON admission.logs TO board_admission_owner;
GRANT USAGE ON SEQUENCE admission.logs_id_seq TO board_admission_owner;

CREATE FUNCTION content.lock_content_admission(p_board text,p_peer text)
RETURNS TABLE(revision bigint,banned boolean)
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $$
DECLARE v_peer inet;
BEGIN
    IF NOT EXISTS(SELECT 1 FROM content.boards b WHERE b.slug=p_board AND NOT b.staff_only) THEN
        RAISE EXCEPTION 'Public board not found.' USING ERRCODE='P0002';
    END IF;
    SELECT p.revision INTO revision FROM admission.policy p WHERE singleton FOR SHARE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Content admission policy is unavailable.' USING ERRCODE='55000'; END IF;
    banned:=false;
    IF p_peer IS NOT NULL THEN
        v_peer:=p_peer::inet;
        IF masklen(v_peer)<>(CASE family(v_peer) WHEN 4 THEN 32 ELSE 128 END) THEN
            RAISE EXCEPTION 'Invalid content admission peer.' USING ERRCODE='23514';
        END IF;
        -- Board -> policy -> exact peer -> anonymous state is the posting lock
        -- order. Different boards cannot race the same peer's global auto-ban.
        PERFORM pg_advisory_xact_lock(hashtextextended('26chan:admission:'||host(v_peer),0));
        banned:=EXISTS(SELECT 1 FROM admission.bans b WHERE b.peer=v_peer AND b.active
            AND (b.expires_at IS NULL OR b.expires_at>clock_timestamp()));
    END IF;
    RETURN NEXT;
END $$;

CREATE FUNCTION content.content_admission_rules(p_board text)
RETURNS TABLE(id bigint,board text,pattern text,regex boolean,autosage boolean,log boolean,
    quiet boolean,lenient boolean,ops_only boolean,min_count integer,ban_days integer)
LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $$
    SELECT r.id,r.board,r.pattern,r.regex,r.autosage,r.log,r.quiet,r.lenient,r.ops_only,r.min_count,r.ban_days
    FROM admission.rules r WHERE r.active AND (r.board='' OR r.board=p_board)
        AND EXISTS(SELECT 1 FROM content.boards b WHERE b.slug=p_board AND NOT b.staff_only)
    ORDER BY r.position,r.id LIMIT 129
$$;

CREATE FUNCTION content.record_content_admission(p_board text,p_peer text,p_revision bigint,
    p_rule bigint,p_kind text,p_parent bigint,p_name text,p_subject text,p_comment text,p_filename text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $$
DECLARE v_revision bigint; r admission.rules%ROWTYPE; c admission.capacity%ROWTYPE;
    v_peer inet; v_days integer; v_now timestamptz:=clock_timestamp(); v_reason text;
BEGIN
    SELECT revision INTO v_revision FROM admission.policy WHERE singleton FOR SHARE;
    IF NOT FOUND OR p_revision IS NULL OR v_revision<>p_revision THEN
        RAISE EXCEPTION 'Content admission policy changed.' USING ERRCODE='55000';
    END IF;
    IF p_kind IS NULL OR p_kind NOT IN ('filename','autosage','log','reject','quiet')
        OR p_peer IS NULL OR p_parent IS NULL OR p_parent<0 OR p_name IS NULL OR octet_length(p_name)>2048
        OR p_subject IS NULL OR octet_length(p_subject)>2048 OR p_comment IS NULL OR octet_length(p_comment)>131072
        OR p_filename IS NULL OR octet_length(p_filename)>1024
        OR NOT EXISTS(SELECT 1 FROM content.boards b WHERE b.slug=p_board AND NOT b.staff_only) THEN
        RAISE EXCEPTION 'Invalid content admission effect.' USING ERRCODE='23514';
    END IF;
    v_peer:=p_peer::inet;
    IF masklen(v_peer)<>(CASE family(v_peer) WHEN 4 THEN 32 ELSE 128 END) THEN
        RAISE EXCEPTION 'Invalid content admission peer.' USING ERRCODE='23514';
    END IF;
    PERFORM pg_advisory_xact_lock(hashtextextended('26chan:admission:'||host(v_peer),0));
    IF p_kind='filename' AND p_rule IS NULL AND left(p_filename,3)='php'
        AND octet_length(p_filename)>=5 AND strpos(p_filename,'.')=0
        AND position(decode('0a','hex') IN substring(convert_to(p_filename,'UTF8') FROM 4 FOR 2))=0 THEN
        v_days:=14; v_reason:='filename';
    ELSE
        SELECT * INTO r FROM admission.rules WHERE id=p_rule AND active AND (board='' OR board=p_board);
        IF NOT FOUND OR (p_parent>0 AND (r.ops_only OR r.autosage)) OR
            NOT ((p_kind='autosage' AND r.autosage) OR
                 (p_kind='log' AND NOT r.autosage AND r.log) OR
                 (p_kind='reject' AND NOT r.autosage AND NOT r.log AND NOT r.quiet) OR
                 (p_kind='quiet' AND NOT r.autosage AND NOT r.log AND r.quiet)) THEN
            RAISE EXCEPTION 'Content admission effect is not permitted.' USING ERRCODE='23514';
        END IF;
        v_days:=CASE WHEN p_kind IN ('reject','quiet') THEN r.ban_days ELSE 0 END;
        v_reason:='content';
    END IF;
    -- Capacity has a separate row from policy. Readers never upgrade a shared
    -- policy lock while another board is evaluating the same generation.
    SELECT * INTO c FROM admission.capacity WHERE singleton FOR UPDATE;
    IF NOT FOUND THEN RAISE EXCEPTION 'Content admission capacity is unavailable.' USING ERRCODE='55000'; END IF;
    IF p_rule IS NOT NULL THEN
        IF NOT EXISTS(SELECT 1 FROM admission.hits WHERE rule_id=p_rule AND peer=v_peer)
            AND (SELECT count(*) FROM (SELECT 1 FROM admission.hits LIMIT c.hit_limit) bounded)>=c.hit_limit THEN
            RAISE EXCEPTION 'Content admission hit capacity exhausted.' USING ERRCODE='53300';
        END IF;
        INSERT INTO admission.hits(rule_id,peer,board,last_hit,count) VALUES(p_rule,v_peer,p_board,v_now,1)
            ON CONFLICT(rule_id,peer) DO UPDATE SET count=admission.hits.count+1,last_hit=v_now,board=p_board
            WHERE admission.hits.last_hit<=v_now-interval '1 hour';
    END IF;
    IF p_kind='log' THEN
        IF (SELECT count(*) FROM (SELECT 1 FROM admission.logs LIMIT c.log_limit) bounded)>=c.log_limit THEN
            RAISE EXCEPTION 'Content admission log capacity exhausted.' USING ERRCODE='53300';
        END IF;
        INSERT INTO admission.logs(rule_id,board,parent,peer,name,subject,comment,filename)
        VALUES(p_rule,p_board,p_parent,v_peer,p_name,p_subject,p_comment,p_filename);
    END IF;
    IF v_days<>0 THEN
        IF NOT EXISTS(SELECT 1 FROM admission.bans WHERE peer=v_peer)
            AND (SELECT count(*) FROM (SELECT 1 FROM admission.bans LIMIT c.ban_limit) bounded)>=c.ban_limit THEN
            RAISE EXCEPTION 'Content admission ban capacity exhausted.' USING ERRCODE='53300';
        END IF;
        INSERT INTO admission.bans(peer,board,rule_id,reason,expires_at)
        VALUES(v_peer,p_board,p_rule,v_reason,CASE WHEN v_days=-1 THEN NULL
            ELSE date_trunc('day',v_now AT TIME ZONE 'UTC') AT TIME ZONE 'UTC' + make_interval(days=>v_days) END)
        ON CONFLICT(peer) DO UPDATE SET board=p_board,rule_id=p_rule,reason=v_reason,
            expires_at=EXCLUDED.expires_at,created_at=v_now,active=true;
    END IF;
END $$;

-- Shared with OP membership checks: take the final activity lock strength now,
-- before reading ages/counters used by lenient content rules.
CREATE FUNCTION content.lock_anonymous_session(p_token bytea)
RETURNS TABLE(created_at bigint,network_at bigint,address_at bigint,environment_at bigint,
    activity_at bigint,action_at bigint,verified_level smallint,posts smallint,images smallint,
    threads smallint,reports smallint,pending smallint,change_score smallint,
    network_hash bytea,address_hash bytea,environment_hash bytea)
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $$
BEGIN
    PERFORM s.token_hash FROM post_secrets.anonymous_sessions s WHERE s.token_hash=p_token
        AND octet_length(p_token)=32 AND s.expires_at>extract(epoch FROM clock_timestamp())::bigint FOR UPDATE;
    IF NOT FOUND THEN RETURN; END IF;
    RETURN QUERY SELECT * FROM content.anonymous_session(p_token);
END $$;
REVOKE ALL ON FUNCTION content.lock_content_admission(text,text),content.content_admission_rules(text),
    content.record_content_admission(text,text,bigint,bigint,text,bigint,text,text,text,text),
    content.lock_anonymous_session(bytea) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION content.lock_content_admission(text,text),content.content_admission_rules(text),
    content.record_content_admission(text,text,bigint,bigint,text,bigint,text,text,text,text),
    content.lock_anonymous_session(bytea) TO board_public;
GRANT CREATE ON SCHEMA content TO board_admission_owner,board_anonymous_owner;
ALTER FUNCTION content.lock_content_admission(text,text) OWNER TO board_admission_owner;
ALTER FUNCTION content.content_admission_rules(text) OWNER TO board_admission_owner;
ALTER FUNCTION content.record_content_admission(text,text,bigint,bigint,text,bigint,text,text,text,text) OWNER TO board_admission_owner;
ALTER FUNCTION content.lock_anonymous_session(bytea) OWNER TO board_anonymous_owner;
REVOKE CREATE ON SCHEMA content FROM board_admission_owner,board_anonymous_owner;

CREATE FUNCTION content.attachment_upload_filename(p_job text,p_capability text)
RETURNS text LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $$
DECLARE v_filename text;
BEGIN
    -- Preserve the insertion lock order and verify capability expiry after
    -- waiting. Unready or revoked media cannot create content-filter effects.
    PERFORM j.id FROM media.jobs j WHERE j.id=p_job FOR UPDATE;
    PERFORM content.check_attachment_upload(p_job,p_capability);
    SELECT j.filename INTO v_filename FROM media.jobs j WHERE j.id=p_job AND j.state='published'
        AND EXISTS(SELECT 1 FROM media.assets a WHERE a.job_id=j.id AND a.state='approved');
    IF NOT FOUND THEN RAISE EXCEPTION 'Attachment is not approved.' USING ERRCODE='P0001'; END IF;
    RETURN v_filename;
END $$;
REVOKE ALL ON FUNCTION content.attachment_upload_filename(text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION content.attachment_upload_filename(text,text) TO board_public;
GRANT CREATE ON SCHEMA content TO board_attachment_owner;
ALTER FUNCTION content.attachment_upload_filename(text,text) OWNER TO board_attachment_owner;
REVOKE CREATE ON SCHEMA content FROM board_attachment_owner;

CREATE FUNCTION content.stamp_content_autosage() RETURNS trigger
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,pg_temp AS $$
DECLARE v_rule text:=nullif(current_setting('board.content_autosage',true),'');
    v_revision text:=nullif(current_setting('board.content_admission_revision',true),'');
    v_peer text:=nullif(current_setting('board.content_admission_peer',true),'');
BEGIN
    IF v_rule IS NULL THEN RETURN NEW; END IF;
    IF v_rule !~ '^[1-9][0-9]{0,18}$' OR v_revision IS NULL OR v_revision !~ '^[1-9][0-9]{0,18}$'
        OR v_peer IS NULL OR NOT EXISTS(SELECT 1 FROM admission.policy p WHERE p.singleton AND p.revision=v_revision::bigint)
        OR NOT EXISTS(SELECT 1 FROM admission.rules r WHERE r.id=v_rule::bigint AND r.active AND r.autosage
            AND (r.board='' OR r.board=NEW.board))
        OR NOT EXISTS(SELECT 1 FROM admission.hits h WHERE h.rule_id=v_rule::bigint AND h.peer=v_peer::inet
            AND h.last_hit>clock_timestamp()-interval '1 hour') THEN
        RAISE EXCEPTION 'Content autosage authority is unavailable.' USING ERRCODE='23514';
    END IF;
    NEW.permasage:=true;
    RETURN NEW;
END $$;
REVOKE ALL ON FUNCTION content.stamp_content_autosage() FROM PUBLIC;
CREATE TRIGGER stamp_content_autosage BEFORE INSERT ON content.threads
    FOR EACH ROW EXECUTE FUNCTION content.stamp_content_autosage();
GRANT CREATE ON SCHEMA content TO board_admission_owner;
ALTER FUNCTION content.stamp_content_autosage() OWNER TO board_admission_owner;
REVOKE CREATE ON SCHEMA content FROM board_admission_owner;
