-- Source SPOILER_THUMB choices; independent of SPOILER_NUM and spoiler enablement.
ALTER TABLE content.boards ADD COLUMN spoiler_thumbnail_assets text[] NOT NULL DEFAULT ARRAY['spoiler.png']::text[]
  CHECK (array_ndims(spoiler_thumbnail_assets)=1 AND array_lower(spoiler_thumbnail_assets,1)=1
    AND cardinality(spoiler_thumbnail_assets) BETWEEN 1 AND 64
    AND array_position(spoiler_thumbnail_assets,NULL) IS NULL
    AND spoiler_thumbnail_assets <@ ARRAY['spoiler-a1.png','spoiler-co1.png','spoiler-co2.png','spoiler-co3.png','spoiler-co4.png','spoiler-co5.png','spoiler-jp1.png','spoiler-lit1.png','spoiler-m1.png','spoiler-m2.png','spoiler-m3.png','spoiler-m4.png','spoiler-mlp1.png','spoiler-s4s1.png','spoiler-s4s2.png','spoiler-s4s3.png','spoiler-s4s4.png','spoiler-s4s5.png','spoiler-s4s6.png','spoiler-tg1.png','spoiler-tg2.png','spoiler-tv1.png','spoiler-tv2.png','spoiler-tv3.png','spoiler-tv4.png','spoiler-tv5.png','spoiler-v1.png','spoiler-vg1.png','spoiler-vmg1.png','spoiler-vmg2.png','spoiler-vmg3.png','spoiler-vp1.png','spoiler-vr1.png','spoiler-vr2.png','spoiler-vrpg1.png','spoiler-vrpg2.png','spoiler-vrpg3.png','spoiler-vst.png','spoiler-vt1.png','spoiler-vt2.png','spoiler-vt3.png','spoiler.png']::text[]);
UPDATE content.boards b SET spoiler_thumbnail_assets=policy.assets
FROM (VALUES
('a',ARRAY['spoiler-a1.png']::text[]),
('aco',ARRAY['spoiler.png']::text[]),
('c',ARRAY['spoiler.png']::text[]),
('d',ARRAY['spoiler.png']::text[]),
('e',ARRAY['spoiler.png']::text[]),
('f',ARRAY['spoiler.png']::text[]),
('g',ARRAY['spoiler.png']::text[]),
('gif',ARRAY['spoiler.png']::text[]),
('h',ARRAY['spoiler.png']::text[]),
('his',ARRAY['spoiler.png']::text[]),
('hr',ARRAY['spoiler.png']::text[]),
('k',ARRAY['spoiler.png']::text[]),
('m',ARRAY['spoiler-m1.png','spoiler-m2.png','spoiler-m3.png','spoiler-m4.png']::text[]),
('n',ARRAY['spoiler.png']::text[]),
('o',ARRAY['spoiler.png']::text[]),
('p',ARRAY['spoiler.png']::text[]),
('r',ARRAY['spoiler.png']::text[]),
('s',ARRAY['spoiler.png']::text[]),
('t',ARRAY['spoiler.png']::text[]),
('u',ARRAY['spoiler.png']::text[]),
('v',ARRAY['spoiler-v1.png']::text[]),
('w',ARRAY['spoiler.png']::text[]),
('wg',ARRAY['spoiler.png']::text[]),
('i',ARRAY['spoiler.png']::text[]),
('ic',ARRAY['spoiler.png']::text[]),
('cm',ARRAY['spoiler.png']::text[]),
('y',ARRAY['spoiler.png']::text[]),
('an',ARRAY['spoiler.png']::text[]),
('cgl',ARRAY['spoiler.png']::text[]),
('ck',ARRAY['spoiler.png']::text[]),
('co',ARRAY['spoiler-co1.png','spoiler-co2.png','spoiler-co3.png','spoiler-co4.png','spoiler-co5.png']::text[]),
('fa',ARRAY['spoiler.png']::text[]),
('fit',ARRAY['spoiler.png']::text[]),
('jp',ARRAY['spoiler-jp1.png']::text[]),
('mlp',ARRAY['spoiler-mlp1.png']::text[]),
('mu',ARRAY['spoiler.png']::text[]),
('po',ARRAY['spoiler.png']::text[]),
('sp',ARRAY['spoiler.png']::text[]),
('tg',ARRAY['spoiler-tg1.png','spoiler-tg2.png']::text[]),
('toy',ARRAY['spoiler.png']::text[]),
('trv',ARRAY['spoiler.png']::text[]),
('tv',ARRAY['spoiler-tv1.png','spoiler-tv2.png','spoiler-tv3.png','spoiler-tv4.png','spoiler-tv5.png']::text[]),
('x',ARRAY['spoiler.png']::text[]),
('b',ARRAY['spoiler.png']::text[]),
('soc',ARRAY['spoiler.png']::text[]),
('r9k',ARRAY['spoiler.png']::text[]),
('test',ARRAY['spoiler.png']::text[]),
('adv',ARRAY['spoiler.png']::text[]),
('lit',ARRAY['spoiler-lit1.png']::text[]),
('int',ARRAY['spoiler.png']::text[]),
('sci',ARRAY['spoiler.png']::text[]),
('3',ARRAY['spoiler.png']::text[]),
('vp',ARRAY['spoiler-vp1.png']::text[]),
('diy',ARRAY['spoiler.png']::text[]),
('pol',ARRAY['spoiler.png']::text[]),
('hc',ARRAY['spoiler.png']::text[]),
('vg',ARRAY['spoiler-vg1.png']::text[]),
('hm',ARRAY['spoiler.png']::text[]),
('j',ARRAY['spoiler.png']::text[]),
('wsg',ARRAY['spoiler.png']::text[]),
('out',ARRAY['spoiler.png']::text[]),
('lgbt',ARRAY['spoiler.png']::text[]),
('vr',ARRAY['spoiler-vr1.png','spoiler-vr2.png']::text[]),
('gd',ARRAY['spoiler.png']::text[]),
('s4s',ARRAY['spoiler-s4s1.png','spoiler-s4s2.png','spoiler-s4s3.png','spoiler-s4s4.png','spoiler-s4s5.png','spoiler-s4s6.png']::text[]),
('biz',ARRAY['spoiler.png']::text[]),
('qa',ARRAY['spoiler.png']::text[]),
('trash',ARRAY['spoiler.png']::text[]),
('news',ARRAY['spoiler-a1.png']::text[]),
('wsr',ARRAY['spoiler.png']::text[]),
('qst',ARRAY['spoiler.png']::text[]),
('bant',ARRAY['spoiler.png']::text[]),
('vip',ARRAY['spoiler.png']::text[]),
('vrpg',ARRAY['spoiler-vrpg1.png','spoiler-vrpg2.png','spoiler-vrpg3.png']::text[]),
('vmg',ARRAY['spoiler-vmg1.png','spoiler-vmg2.png','spoiler-vmg3.png']::text[]),
('vst',ARRAY['spoiler-vst.png']::text[]),
('vt',ARRAY['spoiler-vt1.png','spoiler-vt2.png','spoiler-vt3.png']::text[]),
('vm',ARRAY['spoiler-v1.png']::text[]),
('pw',ARRAY['spoiler.png']::text[]),
('xs',ARRAY['spoiler.png']::text[]),
('asp',ARRAY['spoiler.png']::text[]),
('qb',ARRAY['spoiler.png']::text[])) policy(slug,assets) WHERE b.slug=policy.slug;
