// Test-only generator: exact whole vendor source remains the generated byte prefix.
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {CASES,encodeOwnedCase} from './cases.mjs';
import {decodeReplayCandidateWire} from '../../../apps/public/client/native-replay-data.js';
export const SOURCE=Object.freeze({bytes:110619,sha256:'daea182c52df0c032eadbecb4de8f91f634a61bf82aaf35dda077fab50e68744',version:'0.9.4'});
const here=new URL('./',import.meta.url),root=new URL('../../../',here);
const hash=data=>createHash('sha256').update(data).digest('hex');
export async function expectedFiles(){
  const source=await readFile(new URL('apps/public/vendor/tegaki/0.9.4/tegaki.min.js',root));
  assert.equal(source.length,SOURCE.bytes,'source byte count mismatch');assert.equal(hash(source),SOURCE.sha256,'source SHA-256 mismatch');
  const adapter=await readFile(new URL('consumer-adapter.inc.js',here));
  const data=await readFile(new URL('apps/public/client/native-replay-data.js',root));
  const module=await readFile(new URL('apps/public/static/tegaki/tegaki-0.9.4.v1.js',root));
  assert(module.subarray(0,source.length).equals(source));
  const licenses=module.subarray(source.length).toString().replace(/export \{ Tegaki \};\n$/,'');
  const files=new Map([
    ['consumer-v1.mjs',Buffer.concat([source,Buffer.from(licenses),Buffer.from('\n'),adapter])],['canonical-data.mjs',data],
    ['tegaki.css',await readFile(new URL('apps/public/static/tegaki/tegaki-0.9.4.v1.css',root))],
    ['tegaki-icons.v1.woff',await readFile(new URL('apps/public/static/tegaki/tegaki-icons.v1.woff',root))],
  ]),cases=[];
  for(const item of CASES){const bytes=Buffer.from(encodeOwnedCase(item)),candidate=decodeReplayCandidateWire(bytes);
    assert(candidate.events.length<=96&&item.width<=24&&item.height<=24);const name=`${item.id}.ibr`;files.set(name,bytes);
    cases.push({id:item.id,name,bytes:bytes.length,sha256:hash(bytes),events:candidate.events.length});}
  files.set('core-cases.rs', Buffer.from('// Generated exact owned corpus; logical state/cost checks do not qualify browser pixels.\nconst PROBE_CASES: &[(&str, &str, &[u8])] = &[\n' + cases.map(row => `    (\"${row.id}\", \"${row.sha256}\", include_bytes!(\"${row.name}\")),`).join('\n') + '\n];\n'));
  const manifest={schema:1,consumer:'tegaki-worker-probe-v1',source:SOURCE,adapter:{bytes:adapter.length,sha256:hash(adapter)},
    canonicalAdapter:{bytes:data.length,sha256:hash(data)},artifacts:Object.fromEntries([...files].map(([name,bytes])=>[name,{bytes:bytes.length,sha256:hash(bytes)}])),cases,
    claims:{fixedOwnedCorpusOnly:true,generalAdmission:false,nativeBrowserExecutedHere:false,cssCompositorEquivalence:false,repeatedPresentationInExistingCostModel:false}};
  files.set('manifest.json',Buffer.from(`${JSON.stringify(manifest,null,2)}\n`));return files;
}
export async function build(check=true){const files=await expectedFiles();if(!check)await mkdir(new URL('generated/',here),{recursive:true});
  for(const [name,data] of files){const path=new URL(`generated/${name}`,here);if(check)assert.deepEqual(await readFile(path),data,`generated ${name} drifted`);else await writeFile(path,data);}return files.size;}
if(process.argv[1]===fileURLToPath(import.meta.url)){assert([undefined,'--write'].includes(process.argv[2])&&process.argv.length<=3,'usage: build.mjs [--write]');console.log(`Verified ${await build(process.argv[2]!=='--write')} test-only artifacts; native browser not run.`);}
