<?php
// Fixed source classes only. No application, configuration, database or RPC.
if ($argc < 4) {
    fwrite(STDERR, "Usage: php scripts/extract-wordfilter-unicode-reference.php SOURCE JSON RUST [--check]\n");
    exit(2);
}
$root = realpath($argv[1]);
if (!$root) { throw new RuntimeException('Reference directory is missing.'); }
$hash = 'f5ff2ac132b86fa4889e4312f3c2162ab121854cffeb33505f22bfbd2c65b439';
$source = file_get_contents($root . '/wordfilters/global.php');
if (hash('sha256', $source) !== $hash
    || strpos($source, '/(\b)(s([o0οоօჿ]+)[yуΥ])(\b|[[:alpha:]]{2,4})/iu') === false) {
    throw new RuntimeException('Audited global filter or Unicode pattern differs.');
}
// These are the boundary, suffix and three character classes of that pattern.
$patterns = ['word' => '/^\w$/iu', 'alpha' => '/^[[:alpha:]]$/iu',
    's' => '/^s$/iu', 'o' => '/^[o0οоօჿ]$/iu', 'y' => '/^[yуΥ]$/iu'];
$ranges = array_fill_keys(array_keys($patterns), []);
$starts = array_fill_keys(array_keys($patterns), null);
$counts = array_fill_keys(array_keys($patterns), 0);
$scalars = 0;
// One fixed finite scan, including a final sentinel that closes the last range.
for ($point = 0; $point <= 0x110000; ++$point) {
    $scalar = $point < 0x110000 && !($point >= 0xd800 && $point <= 0xdfff);
    $text = $scalar ? mb_chr($point, 'UTF-8') : '';
    if ($scalar) { ++$scalars; }
    foreach ($patterns as $name => $pattern) {
        $matches = $scalar && preg_match($pattern, $text) === 1;
        if ($matches) { ++$counts[$name]; }
        if ($matches && $starts[$name] === null) { $starts[$name] = $point; }
        elseif (!$matches && $starts[$name] !== null) {
            $ranges[$name][] = [$starts[$name], $point - 1];
            $starts[$name] = null;
        }
    }
}
$fixture = ['reference' => 'operator-supplied 4chan-old checkout',
    'extractor_php' => PHP_VERSION, 'extractor_pcre' => PCRE_VERSION,
    'files' => ['wordfilters/global.php' => $hash], 'scalars' => $scalars,
    'patterns' => $patterns, 'counts' => $counts, 'ranges' => $ranges];
$json = json_encode($fixture, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE
    | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR) . "\n";
$rust = "// Generated by scripts/extract-wordfilter-unicode-reference.php.\n"
    . '// Audited source classes with PHP ' . PHP_VERSION . ', PCRE ' . PCRE_VERSION . ".\n"
    . '// wordfilters/global.php SHA-256: ' . $hash . "\n";
foreach ($ranges as $name => $entries) {
    $items = array_map(fn($range) => sprintf('(0x%x, 0x%x)', $range[0], $range[1]), $entries);
    $declaration = 'pub(super) const ' . strtoupper($name) . ': &[(u32, u32)] = &[';
    $compact = $declaration . implode(', ', $items) . '];';
    if (strlen(implode(', ', $items)) <= 60 && strlen($compact) <= 100) {
        $rust .= "\n" . $compact . "\n";
    } else {
        $rust .= "\n" . $declaration . "\n";
        foreach ($items as $item) { $rust .= '    ' . $item . ",\n"; }
        $rust .= "];\n";
    }
}
if (strlen($json) > 131072 || strlen($rust) > 65536 || $scalars !== 1112064) {
    throw new RuntimeException('Unicode reference exceeds its fixed limits.');
}
if (in_array('--check', $argv, true)) {
    if (file_get_contents($argv[2]) !== $json || file_get_contents($argv[3]) !== $rust) {
        throw new RuntimeException('Unicode reference differs.');
    }
    echo "Wordfilter Unicode reference matches five classes over 1,112,064 scalars.\n";
} else {
    file_put_contents($argv[2], $json);
    file_put_contents($argv[3], $rust);
}
