<?php
// Fixed CP932 conversion and DES vectors only. No application or private data.
if ($argc < 4) {
    fwrite(STDERR, "Usage: php scripts/extract-trip-encoding-reference.php SOURCE JSON RUST [--check]\n");
    exit(2);
}
$root = realpath($argv[1]);
$hash = 'caa787cde52eee4c52d85407b077f18938cd15923458a3d95c0c2c614ce7b445';
if (!$root || !extension_loaded('mbstring')) {
    throw new RuntimeException('Pinned source and mbstring are required.');
}
$source = file_get_contents($root . '/imgboard.php');
if (hash('sha256', $source) !== $hash
    || strpos($source, "mb_convert_encoding(\$name, 'CP932', 'UTF-8')") === false
    || mb_substitute_character() !== 63) {
    throw new RuntimeException('Audited conversion or substitution policy differs.');
}
if (($argv[4] ?? '') === '--worker') {
    $pairs = []; $invalid = []; $scalars = 0;
    for ($point = 0; $point <= 0x10ffff; ++$point) {
        if ($point >= 0xd800 && $point <= 0xdfff) { continue; }
        ++$scalars;
        $encoded = mb_convert_encoding(mb_chr($point, 'UTF-8'), 'CP932', 'UTF-8');
        if (strlen($encoded) < 1 || strlen($encoded) > 2) {
            throw new RuntimeException('CP932 scalar has an unexpected width.');
        }
        if ($point < 128) {
            if ($encoded !== chr($point)) { throw new RuntimeException('ASCII conversion differs.'); }
        } elseif ($encoded !== '?') {
            $pairs[] = [$point, bin2hex($encoded)];
        }
        if ($encoded !== '' && htmlspecialchars($encoded, ENT_COMPAT | ENT_HTML401, 'Shift_JIS') === '') {
            $invalid[] = $point;
        }
    }
    $vectors = [];
    foreach (['', 'a', 'ab', 'abc', 'password', '12345678', '123456789',
        'a:b', 'a;b', 'a<b', 'a=b', 'a>b', 'a?b', 'a@b', 'a[b', 'a\\b',
        'a]b', 'a^b', 'a_b', 'a`b', 'a&b', 'a"b', 'a b', 'a~b', 'a!b',
        'かみ', 'ｋａｍｉ', '漢字', 'ééé', '€', '¥', '‾', '〜', '～', '―', '—',
        '∥', '‖', '−', '－', 'ソソソソソ', '予abcdef', "\u{f8f0}", "\u{f8f1}",
        "\u{f8f2}", "\u{f8f3}", 'a𠀀b', '日本語&"<>'] as $input) {
        $encoded = mb_convert_encoding($input, 'CP932', 'UTF-8');
        $escaped = htmlspecialchars($encoded, ENT_COMPAT | ENT_HTML401, 'Shift_JIS');
        $salt = strtr(preg_replace('/[^\.-z]/', '.', substr($escaped . 'H.', 1, 2)),
            ':;<=>?@[\\]^_`', 'ABCDEFGabcdef');
        $vectors[] = ['input' => $input, 'cp932_hex' => bin2hex($encoded),
            'escaped_hex' => bin2hex($escaped), 'trip' => $escaped === '' ? null : substr(crypt($escaped, $salt), -10)];
    }
    echo json_encode(compact('scalars', 'pairs', 'invalid', 'vectors'), JSON_THROW_ON_ERROR);
    exit(0);
}
$process = proc_open([PHP_BINARY, '-d', 'memory_limit=128M', __FILE__, $root, $argv[2], $argv[3], '--worker'],
    [0 => ['pipe', 'r'], 1 => ['pipe', 'w'], 2 => ['pipe', 'w']], $pipes);
if (!is_resource($process)) { throw new RuntimeException('Conversion worker cannot start.'); }
fclose($pipes[0]); stream_set_blocking($pipes[1], false); stream_set_blocking($pipes[2], false);
$deadline = microtime(true) + 30; $output = ''; $errors = '';
do {
    $output .= stream_get_contents($pipes[1], 1048577 - strlen($output));
    $errors .= stream_get_contents($pipes[2], 2049 - strlen($errors));
    $status = proc_get_status($process);
    if (strlen($output) > 1048576 || strlen($errors) > 2048 || microtime(true) > $deadline) {
        proc_terminate($process, 9); throw new RuntimeException('Conversion worker exceeded bounds.');
    }
    if ($status['running']) { usleep(10000); }
} while ($status['running']);
$output .= stream_get_contents($pipes[1], 1048577 - strlen($output));
$errors .= stream_get_contents($pipes[2], 2049 - strlen($errors));
fclose($pipes[1]); fclose($pipes[2]); proc_close($process);
if ($status['exitcode'] !== 0 || strlen($output) > 1048576 || $errors !== '') {
    throw new RuntimeException('Conversion worker failed.');
}
$result = json_decode($output, true, 32, JSON_THROW_ON_ERROR);
if ($result['scalars'] !== 1112064 || count($result['pairs']) > 10000 || count($result['invalid']) > 128) {
    throw new RuntimeException('Conversion scan differs from its finite bounds.');
}
$fixture = ['reference' => 'operator-supplied 4chan-old checkout', 'extractor_php' => PHP_VERSION,
    'files' => ['imgboard.php' => $hash], 'input_encoding' => 'UTF-8', 'output_encoding' => 'CP932',
    'html_encoding' => 'Shift_JIS', 'substitution' => 63] + $result;
$json = json_encode($fixture, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES
    | JSON_THROW_ON_ERROR) . "\n";
$rust = "// Generated by scripts/extract-trip-encoding-reference.php.\n"
    . '// PHP ' . PHP_VERSION . ", CP932 with substitution 63.\n"
    . '// imgboard.php SHA-256: ' . $hash . "\n\n"
    . "pub(super) const PAIRS: &[(u32, u16)] = &[\n";
foreach ($result['pairs'] as [$point, $hex]) { $rust .= sprintf("    (0x%x, 0x%s),\n", $point, $hex); }
$rust .= "];\n";
if (strlen($json) > 1048576 || strlen($rust) > 262144) { throw new RuntimeException('Conversion output exceeds bounds.'); }
foreach ([$argv[2] => $json, $argv[3] => $rust] as $path => $bytes) {
    if (in_array('--check', $argv, true)) {
        if (file_get_contents($path) !== $bytes) { throw new RuntimeException('Conversion reference differs.'); }
    } elseif (file_put_contents($path, $bytes) !== strlen($bytes)) {
        throw new RuntimeException('Conversion reference cannot be saved.');
    }
}
echo 'CP932: ' . $result['scalars'] . ' scalars, ' . count($result['pairs']) . ' non-ASCII mappings, '
    . count($result['invalid']) . ' invalid Shift_JIS scalars, ' . count($result['vectors']) . " conversion/legacy cases.\n";
