use crate::{AppState, handlers::AppError};
use askama::Template;
use axum::{
    http::{HeaderMap, HeaderValue},
    response::Response,
};
use board_domain::{Line, Token, comment_markup::Tag, word_break::WordPart};
use std::fmt::{self, Write};

/// The byte-oriented source chooses the first sentence longer than six bytes,
/// then keeps complete words through the first boundary at or after byte 60.
fn summarize(comment: &str) -> String {
    let mut without_urls = String::with_capacity(comment.len());
    let mut tail = comment;
    while let Some(start) = tail.find("//") {
        let prefix = &tail[..start];
        let end = tail[start + 2..]
            .bytes()
            .position(php_whitespace)
            .map_or(tail.len(), |end| start + 2 + end);
        // The source's + quantifier requires at least one following byte.
        if end == start + 2 {
            without_urls.push_str(prefix);
            without_urls.push_str("//");
        } else {
            without_urls.push_str(
                prefix
                    .strip_suffix("https:")
                    .or_else(|| prefix.strip_suffix("http:"))
                    .unwrap_or(prefix),
            );
        }
        tail = &tail[end..];
    }
    without_urls.push_str(tail);
    let with_lines = without_urls
        .replace("<br>", "\n")
        .replace("<br/>", "\n")
        .replace("<br />", "\n");
    let first = with_lines
        .split(['\n', '.'])
        .find(|sentence| sentence.len() > 6)
        .unwrap_or_default();
    let end = first
        .bytes()
        .enumerate()
        .find(|(index, byte)| *index >= 60 && php_whitespace(*byte))
        .map_or(first.len(), |(index, _)| index);
    let mut summary = first[..end].to_owned();
    if summary.len() >= 60 {
        summary.push_str("...");
    }
    summary
}

fn php_whitespace(byte: u8) -> bool {
    byte == b' ' || (b'\t'..=b'\r').contains(&byte)
}

fn strip_tags(value: &str) -> String {
    let mut result = String::new();
    let mut in_tag = false;
    let mut quote = None;
    for ch in value.chars() {
        if in_tag {
            if quote == Some(ch) {
                quote = None;
            } else if quote.is_none() && matches!(ch, '\'' | '"') {
                quote = Some(ch);
            } else if quote.is_none() && ch == '>' {
                in_tag = false;
            }
        } else if ch == '<' {
            in_tag = true;
        } else {
            result.push(ch);
        }
    }
    result
}

// Only decode the five entities generated by the typed source serializer.
// Decoding ampersands last prevents interpreting an escaped literal entity.
fn source_text(value: &str) -> String {
    value
        .replace("&lt;", "<")
        .replace("&gt;", ">")
        .replace("&quot;", "\"")
        .replace("&#039;", "'")
        .replace("&amp;", "&")
}

fn item_title(post: &board_store::Post, stored: &str, forced_anon: bool) -> String {
    if !post.subject.is_empty() {
        return post.subject.clone();
    }
    let summary = source_text(&strip_tags(&summarize(stored)));
    if !summary.is_empty() || post.name.is_empty() {
        return summary;
    }
    if forced_anon {
        format!("No. {}", post.id)
    } else {
        format!("No. {} by {}", post.id, creator(post))
    }
}

fn creator(post: &board_store::Post) -> String {
    match &post.trip {
        Some(trip) => format!("{} {trip}", post.name),
        None => post.name.clone(),
    }
}

fn xml(writer: &mut impl Write, value: &str) -> fmt::Result {
    for ch in value.chars() {
        match ch {
            '&' => writer.write_str("&amp;")?,
            '<' => writer.write_str("&lt;")?,
            '>' => writer.write_str("&gt;")?,
            '"' => writer.write_str("&quot;")?,
            '\'' => writer.write_str("&apos;")?,
            // XML 1.0 cannot represent these scalars. Do not produce malformed
            // documents when historical text contains them.
            '\u{0}'..='\u{8}'
            | '\u{b}'..='\u{c}'
            | '\u{e}'..='\u{1f}'
            | '\u{fffe}'
            | '\u{ffff}' => writer.write_char('\u{fffd}')?,
            _ => writer.write_char(ch)?,
        }
    }
    Ok(())
}

struct XmlText<'a, W>(&'a mut W);
impl<W: Write> Write for XmlText<'_, W> {
    fn write_str(&mut self, text: &str) -> fmt::Result {
        xml(self.0, text)
    }
}

#[derive(Template)]
#[template(path = "rss_description.html")]
struct Description<'a> {
    lines: &'a [Line],
    board: &'a str,
    origin: &'a str,
    source: String,
    thumbnail: String,
    spoilers: bool,
    dice: Option<&'a str>,
    fortune: Option<&'a str>,
    color: Option<&'a str>,
}

// lib/rss.php emits saved comment HTML without calling the page's post-number
// callbacks. Keep those labels inert while retaining stored navigation links.
fn saved_comment_lines(mut lines: Vec<Line>) -> Vec<Line> {
    for token in lines.iter_mut().flat_map(|line| &mut line.tokens) {
        if let board_domain::Token::PostQuote(quote) = token {
            *token = board_domain::Token::Text(quote.label().into());
        }
    }
    lines
}

fn write_feed(
    writer: &mut impl Write,
    snapshot: &board_store::RssSnapshot,
    origin: &str,
    media_origin: &str,
) -> Result<(), askama::Error> {
    let board = &snapshot.board;
    let title = format!("/{}/ - {}", board.slug, board.title);
    let board_url = format!("{origin}/{}/", board.slug);
    writer.write_str("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<rss version=\"2.0\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:atom=\"http://www.w3.org/2005/Atom\"><channel><title>")?;
    xml(writer, &title)?;
    writer.write_str("</title><link>")?;
    xml(writer, &board_url)?;
    writer.write_str("</link><description>")?;
    xml(writer, &format!("Threads on {title} at 4chan.org."))?;
    writer.write_str("</description><atom:link href=\"")?;
    xml(writer, &format!("{board_url}index.rss"))?;
    writer.write_str("\" rel=\"self\" type=\"application/rss+xml\"/>")?;
    for post in &snapshot.posts {
        let lines = saved_comment_lines(post.formatted_lines());
        let mut stored =
            crate::catalog::teaser::stored_comment(&lines, &post.board, post.comment_format);
        if let Some(dice) = &post.dice_result {
            stored = format!(
                "<b>{}<br><br></b>{stored}",
                board_domain::source_html_entities(dice)
            );
        }
        if let Some((text, color)) = post
            .fortune_text
            .as_deref()
            .zip(post.fortune_color.as_deref())
        {
            stored.push_str(&format!(
                "<span class=\"fortune\" style=\"color:{}\"><br><br><b>Your fortune: {}</b></span>",
                board_domain::source_html_entities(color),
                board_domain::source_html_entities(text)
            ));
        }
        let title = item_title(post, &stored, board.forced_anon);
        let link = format!("{origin}/{}/thread/{}", board.slug, post.id);
        writer.write_str("<item>")?;
        if !title.is_empty() {
            writer.write_str("<title>")?;
            xml(writer, &title)?;
            writer.write_str("</title>")?;
        }
        writer.write_str("<link>")?;
        xml(writer, &format!("{link}#{}", post.id))?;
        writer.write_str("</link><guid>")?;
        xml(writer, &link)?;
        writer.write_str("</guid><comments>")?;
        xml(writer, &link)?;
        writer.write_str("</comments><pubDate>")?;
        xml(
            writer,
            &post
                .created_at
                .with_timezone(&chrono_tz::America::New_York)
                .format("%a, %d %b %Y %H:%M:%S %Z")
                .to_string(),
        )?;
        writer.write_str("</pubDate>")?;
        if !board.forced_anon {
            writer.write_str("<dc:creator>")?;
            xml(writer, &creator(post))?;
            writer.write_str("</dc:creator>")?;
        }
        let (source, thumbnail) = match &post.attachment {
            Some(file) if !file.file_deleted => (
                format!(
                    "{media_origin}/{}/{}.{}",
                    board.slug,
                    file.tim,
                    file.output_format.extension()
                ),
                if file.spoiler {
                    format!("{origin}/static/catalog/spoiler.png")
                } else {
                    format!("{media_origin}/{}/{}s.jpg", board.slug, file.tim)
                },
            ),
            _ => (String::new(), String::new()),
        };
        writer.write_str("<description>")?;
        Description {
            lines: &lines,
            board: &post.board,
            origin,
            source,
            thumbnail,
            spoilers: stored.contains("[spoiler"),
            dice: post.dice_result.as_deref(),
            fortune: post.fortune_text.as_deref(),
            color: post.fortune_color.as_deref(),
        }
        .render_into(&mut XmlText(writer))?;
        writer.write_str("</description></item>")?;
    }
    writer.write_str("</channel></rss>")?;
    Ok(())
}

pub(crate) async fn feed(
    state: &AppState,
    board: &str,
    headers: &HeaderMap,
) -> Result<Response, AppError> {
    let snapshot = board_store::rss_snapshot(&state.pool, board).await?;
    let mut writer = state.limits.response_writer(usize::MAX);
    let media_origin = state
        .media
        .as_ref()
        .map(|media| media.settings.origin.as_string())
        .unwrap_or_else(|| state.origin.clone());
    write_feed(&mut writer, &snapshot, &state.origin, &media_origin)
        .map_err(|_| crate::output::unavailable())?;
    let bytes = writer.finish().map_err(|_| crate::output::unavailable())?;
    // The hash covers settings, selections, text and actual attachment state.
    // Board-wide deletions do not necessarily advance a surviving post date.
    let mut response = crate::api::bytes_response(bytes, None, headers)?;
    response.headers_mut().insert(
        "content-type",
        HeaderValue::from_static("application/rss+xml; charset=utf-8"),
    );
    Ok(response)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn summaries_match_the_original_byte_and_word_boundaries() {
        let fixture: serde_json::Value =
            serde_json::from_str(include_str!("../../../fixtures/rss-reference.json")).unwrap();
        for case in fixture["summaries"].as_array().unwrap() {
            let input = case["input"].as_str().unwrap();
            let summary = summarize(input);
            assert_eq!(summary, case["summary"], "{input:?}");
            assert_eq!(strip_tags(&summary), case["title"], "{input:?}");
        }
    }

    #[test]
    fn xml_escapes_untrusted_text_and_replaces_forbidden_scalars() {
        let mut rendered = String::new();
        xml(&mut rendered, "<script>&\"'\u{1}\u{fffe}\n界]]>").unwrap();
        assert_eq!(rendered, "&lt;script&gt;&amp;&quot;&apos;��\n界]]&gt;");
        assert_eq!(source_text("&amp;lt;&lt;&#039;&quot;"), "&lt;<'\"");
    }

    #[test]
    fn feed_descriptions_keep_links_usable_outside_the_board_origin() {
        let lines = saved_comment_lines(board_domain::parse_post_comment_on_board(
            ">>12 >>>/g/34 >>>/g/catalog >>>/g/rules/3 https://www.4chan.org/faq <script>",
            104,
            "test",
        ));
        let description = Description {
            lines: &lines,
            board: "test",
            origin: "https://boards.example",
            source: "https://media.example/test/42.png".into(),
            thumbnail: "https://media.example/test/42s.jpg".into(),
            spoilers: false,
            dice: None,
            fortune: None,
            color: None,
        }
        .render()
        .unwrap();
        for href in [
            "https://boards.example/g/catalog",
            "https://boards.example/rules#g3",
            "https://www.4chan.org/faq",
            "https://media.example/test/42.png",
        ] {
            assert!(
                description.contains(&format!("href=\"{href}\"")),
                "{description}"
            );
        }
        assert!(description.contains("src=\"https://media.example/test/42s.jpg\""));
        assert!(!description.contains("<script>"));
        assert!(!description.contains("/post/"));
        assert!(description.contains("&#62;&#62;12 &#62;&#62;&#62;/g/34"));
    }

    #[test]
    fn numeric_feed_quotes_match_the_extracted_saved_comment_boundary() {
        let fixture: serde_json::Value =
            serde_json::from_str(include_str!("../../../fixtures/rss-reference.json")).unwrap();
        let row = fixture["rows"].as_array().unwrap().last().unwrap();
        assert_eq!(row["sub"], "Stored quotes");
        let source = row["com"].as_str().unwrap();
        assert!(fixture["feed"].as_str().unwrap().contains(source));
        let input = source_text(source.split(" <a ").next().unwrap());
        for format in (104..=111).chain(120..=127) {
            let parsed = board_domain::parse_post_comment_on_board(&input, format, "test");
            // Page parsing retains identities for snapshot resolution.
            assert!(
                parsed
                    .iter()
                    .flat_map(|line| &line.tokens)
                    .any(|token| { matches!(token, board_domain::Token::PostQuote(_)) })
            );
            let lines = saved_comment_lines(parsed);
            let description = Description {
                lines: &lines,
                board: "test",
                origin: "https://boards.example",
                source: String::new(),
                thumbnail: String::new(),
                spoilers: false,
                dice: None,
                fortune: None,
                color: None,
            }
            .render()
            .unwrap();
            assert!(!description.contains("<a"), "{format}: {description}");
            assert!(!description.contains("deadlink"));
            let xml = format!("<root>{description}</root>");
            let document = roxmltree::Document::parse(&xml).unwrap();
            assert_eq!(
                document.root_element().text().unwrap().trim(),
                input,
                "{format}"
            );
        }
    }

    #[test]
    fn feed_descriptions_render_retained_randomizers_and_escape_their_text() {
        let lines = board_domain::parse_post_comment_on_board("ordinary comment", 104, "b");
        let description = Description {
            lines: &lines,
            board: "b",
            origin: "https://boards.example",
            source: String::new(),
            thumbnail: String::new(),
            spoilers: false,
            dice: Some("Rolled 1 (1d1)"),
            fortune: Some("<script> & fortune"),
            color: Some("#7fec11"),
        }
        .render()
        .unwrap();
        assert!(
            description
                .trim_start()
                .starts_with("<b>Rolled 1 (1d1)<br><br></b>")
        );
        assert!(description.contains("ordinary comment"));
        assert!(description.contains("style=\"color:#7fec11\""));
        assert!(description.contains("Your fortune: &#60;script&#62; &#38; fortune"));
        assert!(!description.contains("<script>"));
    }
}
