//! Release-owned public UI bytes, never upload storage or a filesystem server.
use axum::{Router, http::header, routing::get};

pub(crate) const CATALOG_SCRIPT_PATH: &str = "/static/catalog-preferences.v1.js";
pub(crate) const WATCHER_SCRIPT_PATH: &str = "/static/thread-watcher.v1.js";
pub(crate) const WATCHER_CORE_PATH: &str = "/static/thread-watcher-core.v1.js";
pub(crate) const POST_TRACKING_PATH: &str = "/static/post-tracking.v1.js";
pub(crate) const NATIVE_SETTINGS_PATH: &str = "/static/native-settings.v1.js";
pub(crate) const WATCHER_POSITION_PATH: &str = "/static/watcher-position.v1.js";

const ASSETS: &[(&str, &str, &[u8])] = &[
    (
        "/static/catalog/filedeleted-res.gif",
        "image/gif",
        include_bytes!("../static/catalog/filedeleted-res.gif"),
    ),
    (
        "/static/catalog/nofile.png",
        "image/png",
        include_bytes!("../static/catalog/nofile.png"),
    ),
    (
        "/static/catalog/spoiler.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler.png"),
    ),
    (
        "/static/catalog/sticky.gif",
        "image/gif",
        include_bytes!("../static/catalog/sticky.gif"),
    ),
    (
        "/static/catalog/closed.gif",
        "image/gif",
        include_bytes!("../static/catalog/closed.gif"),
    ),
    (
        "/static/catalog/sticky@2x.gif",
        "image/gif",
        include_bytes!("../static/catalog/sticky@2x.gif"),
    ),
    (
        "/static/catalog/closed@2x.gif",
        "image/gif",
        include_bytes!("../static/catalog/closed@2x.gif"),
    ),
    (
        "/static/watcher/futaba/watch_thread_off.png",
        "image/png",
        include_bytes!("../static/watcher/futaba/watch_thread_off.png"),
    ),
    (
        "/static/watcher/futaba/watch_thread_off@2x.png",
        "image/png",
        include_bytes!("../static/watcher/futaba/watch_thread_off@2x.png"),
    ),
    (
        "/static/watcher/futaba/watch_thread_on.png",
        "image/png",
        include_bytes!("../static/watcher/futaba/watch_thread_on.png"),
    ),
    (
        "/static/watcher/futaba/watch_thread_on@2x.png",
        "image/png",
        include_bytes!("../static/watcher/futaba/watch_thread_on@2x.png"),
    ),
    (
        "/static/watcher/futaba/refresh.png",
        "image/png",
        include_bytes!("../static/watcher/futaba/refresh.png"),
    ),
    (
        "/static/watcher/futaba/refresh@2x.png",
        "image/png",
        include_bytes!("../static/watcher/futaba/refresh@2x.png"),
    ),
    (
        "/static/watcher/futaba/cross.png",
        "image/png",
        include_bytes!("../static/watcher/futaba/cross.png"),
    ),
    (
        "/static/watcher/futaba/cross@2x.png",
        "image/png",
        include_bytes!("../static/watcher/futaba/cross@2x.png"),
    ),
    (
        "/static/watcher/futaba/post_expand_rotate.gif",
        "image/gif",
        include_bytes!("../static/watcher/futaba/post_expand_rotate.gif"),
    ),
    (
        "/static/watcher/futaba/post_expand_rotate@2x.gif",
        "image/gif",
        include_bytes!("../static/watcher/futaba/post_expand_rotate@2x.gif"),
    ),
    (
        "/static/watcher/burichan/watch_thread_off.png",
        "image/png",
        include_bytes!("../static/watcher/burichan/watch_thread_off.png"),
    ),
    (
        "/static/watcher/burichan/watch_thread_off@2x.png",
        "image/png",
        include_bytes!("../static/watcher/burichan/watch_thread_off@2x.png"),
    ),
    (
        "/static/watcher/burichan/watch_thread_on.png",
        "image/png",
        include_bytes!("../static/watcher/burichan/watch_thread_on.png"),
    ),
    (
        "/static/watcher/burichan/watch_thread_on@2x.png",
        "image/png",
        include_bytes!("../static/watcher/burichan/watch_thread_on@2x.png"),
    ),
    (
        "/static/watcher/burichan/refresh.png",
        "image/png",
        include_bytes!("../static/watcher/burichan/refresh.png"),
    ),
    (
        "/static/watcher/burichan/refresh@2x.png",
        "image/png",
        include_bytes!("../static/watcher/burichan/refresh@2x.png"),
    ),
    (
        "/static/watcher/burichan/cross.png",
        "image/png",
        include_bytes!("../static/watcher/burichan/cross.png"),
    ),
    (
        "/static/watcher/burichan/cross@2x.png",
        "image/png",
        include_bytes!("../static/watcher/burichan/cross@2x.png"),
    ),
    (
        "/static/watcher/burichan/post_expand_rotate.gif",
        "image/gif",
        include_bytes!("../static/watcher/burichan/post_expand_rotate.gif"),
    ),
    (
        "/static/watcher/burichan/post_expand_rotate@2x.gif",
        "image/gif",
        include_bytes!("../static/watcher/burichan/post_expand_rotate@2x.gif"),
    ),
    (
        "/static/watcher/tomorrow/watch_thread_off.png",
        "image/png",
        include_bytes!("../static/watcher/tomorrow/watch_thread_off.png"),
    ),
    (
        "/static/watcher/tomorrow/watch_thread_off@2x.png",
        "image/png",
        include_bytes!("../static/watcher/tomorrow/watch_thread_off@2x.png"),
    ),
    (
        "/static/watcher/tomorrow/watch_thread_on.png",
        "image/png",
        include_bytes!("../static/watcher/tomorrow/watch_thread_on.png"),
    ),
    (
        "/static/watcher/tomorrow/watch_thread_on@2x.png",
        "image/png",
        include_bytes!("../static/watcher/tomorrow/watch_thread_on@2x.png"),
    ),
    (
        "/static/watcher/tomorrow/refresh.png",
        "image/png",
        include_bytes!("../static/watcher/tomorrow/refresh.png"),
    ),
    (
        "/static/watcher/tomorrow/refresh@2x.png",
        "image/png",
        include_bytes!("../static/watcher/tomorrow/refresh@2x.png"),
    ),
    (
        "/static/watcher/tomorrow/cross.png",
        "image/png",
        include_bytes!("../static/watcher/tomorrow/cross.png"),
    ),
    (
        "/static/watcher/tomorrow/cross@2x.png",
        "image/png",
        include_bytes!("../static/watcher/tomorrow/cross@2x.png"),
    ),
    (
        "/static/watcher/tomorrow/post_expand_rotate.gif",
        "image/gif",
        include_bytes!("../static/watcher/tomorrow/post_expand_rotate.gif"),
    ),
    (
        "/static/watcher/tomorrow/post_expand_rotate@2x.gif",
        "image/gif",
        include_bytes!("../static/watcher/tomorrow/post_expand_rotate@2x.gif"),
    ),
    (
        "/static/watcher/photon/watch_thread_off.png",
        "image/png",
        include_bytes!("../static/watcher/photon/watch_thread_off.png"),
    ),
    (
        "/static/watcher/photon/watch_thread_off@2x.png",
        "image/png",
        include_bytes!("../static/watcher/photon/watch_thread_off@2x.png"),
    ),
    (
        "/static/watcher/photon/watch_thread_on.png",
        "image/png",
        include_bytes!("../static/watcher/photon/watch_thread_on.png"),
    ),
    (
        "/static/watcher/photon/watch_thread_on@2x.png",
        "image/png",
        include_bytes!("../static/watcher/photon/watch_thread_on@2x.png"),
    ),
    (
        "/static/watcher/photon/refresh.png",
        "image/png",
        include_bytes!("../static/watcher/photon/refresh.png"),
    ),
    (
        "/static/watcher/photon/refresh@2x.png",
        "image/png",
        include_bytes!("../static/watcher/photon/refresh@2x.png"),
    ),
    (
        "/static/watcher/photon/cross.png",
        "image/png",
        include_bytes!("../static/watcher/photon/cross.png"),
    ),
    (
        "/static/watcher/photon/cross@2x.png",
        "image/png",
        include_bytes!("../static/watcher/photon/cross@2x.png"),
    ),
    (
        "/static/watcher/photon/post_expand_rotate.gif",
        "image/gif",
        include_bytes!("../static/watcher/photon/post_expand_rotate.gif"),
    ),
    (
        "/static/watcher/photon/post_expand_rotate@2x.gif",
        "image/gif",
        include_bytes!("../static/watcher/photon/post_expand_rotate@2x.gif"),
    ),
    (
        "/static/watcher/buttonfade-blue.png",
        "image/png",
        include_bytes!("../static/watcher/buttonfade-blue.png"),
    ),
    (
        "/static/watcher/buttonfade.png",
        "image/png",
        include_bytes!("../static/watcher/buttonfade.png"),
    ),
];

pub(crate) fn routes<S: Clone + Send + Sync + 'static>() -> Router<S> {
    let mut router = Router::new();
    for &(path, mime, bytes) in ASSETS {
        router = router.route(
            path,
            get(move || async move {
                (
                    [
                        (header::CONTENT_TYPE, mime),
                        (header::CACHE_CONTROL, "public, max-age=0, must-revalidate"),
                    ],
                    bytes,
                )
            }),
        );
    }
    for (path, bytes) in [
        (
            WATCHER_POSITION_PATH,
            include_bytes!("../static/watcher-position.v1.js").as_slice(),
        ),
        (
            NATIVE_SETTINGS_PATH,
            include_bytes!("../static/native-settings.v1.js").as_slice(),
        ),
        (
            POST_TRACKING_PATH,
            include_bytes!("../static/post-tracking.v1.js").as_slice(),
        ),
        (
            CATALOG_SCRIPT_PATH,
            include_bytes!("../static/catalog-preferences.v1.js").as_slice(),
        ),
        (
            WATCHER_SCRIPT_PATH,
            include_bytes!("../static/thread-watcher.v1.js").as_slice(),
        ),
        (
            WATCHER_CORE_PATH,
            include_bytes!("../static/thread-watcher-core.v1.js").as_slice(),
        ),
    ] {
        router = router.route(
            path,
            get(move || async move {
                (
                    [
                        (header::CONTENT_TYPE, "text/javascript; charset=utf-8"),
                        (header::CACHE_CONTROL, "public, max-age=0, must-revalidate"),
                    ],
                    bytes,
                )
            }),
        );
    }
    router
}

pub(crate) fn image_sources(origin: &str) -> String {
    ASSETS
        .iter()
        .map(|(path, _, _)| format!("{origin}{path}"))
        .collect::<Vec<_>>()
        .join(" ")
}
