//! Release-owned public UI bytes, never upload storage or a filesystem server.
use axum::{Router, http::header, routing::get};

pub(crate) const NATIVE_BLOTTER_PATH: &str = "/static/native-blotter.v1.js";
pub(crate) const REPORT_POPUP_PATH: &str = "/static/report-popup.v1.js";
pub(crate) const CATALOG_SCRIPT_PATH: &str = "/static/catalog-preferences.v1.js";
pub(crate) const CATALOG_FILTER_PATH: &str = "/static/catalog-filters.v1.js";
pub(crate) const CATALOG_FILTER_CORE_PATH: &str = "/static/catalog-filter-core.v1.js";
pub(crate) const CATALOG_THEME_PATH: &str = "/static/catalog-theme.v1.js";
pub(crate) const WATCHER_SCRIPT_PATH: &str = "/static/thread-watcher.v1.js";
pub(crate) const WATCHER_CORE_PATH: &str = "/static/thread-watcher-core.v1.js";
pub(crate) const POST_TRACKING_PATH: &str = "/static/post-tracking.v1.js";
pub(crate) const NATIVE_SETTINGS_PATH: &str = "/static/native-settings.v1.js";
pub(crate) const WATCHER_POSITION_PATH: &str = "/static/watcher-position.v1.js";
pub(crate) const NATIVE_FILTER_PATH: &str = "/static/native-filter.v1.js";
pub(crate) const NATIVE_QUICK_REPLY_PATH: &str = "/static/native-quick-reply.v1.js";
pub(crate) const NATIVE_BACKLINKS_PATH: &str = "/static/native-backlinks.v1.js";
pub(crate) const NATIVE_POST_DELETION_PATH: &str = "/static/native-post-deletion.v1.js";
pub(crate) const NATIVE_IMAGES_PATH: &str = "/static/native-images.v1.js";
pub(crate) const NATIVE_DISPLAY_PATH: &str = "/static/native-display.v1.js";
pub(crate) const NATIVE_POST_TOOLTIPS_PATH: &str = "/static/native-post-tooltips.v1.js";
pub(crate) const NATIVE_THREAD_CONTROLS_PATH: &str = "/static/native-thread-controls.v1.js";
pub(crate) const NATIVE_THREAD_STATS_PATH: &str = "/static/native-thread-stats.v1.js";
pub(crate) const NATIVE_NAVIGATION_PATH: &str = "/static/native-navigation.v1.js";
pub(crate) const PAGE_CHROME_PATH: &str = "/static/page-chrome.v1.js";
pub(crate) const NATIVE_LAYOUT_PATH: &str = "/static/native-layout.v1.js";
pub(crate) const NATIVE_EMBEDS_PATH: &str = "/static/native-embeds.v1.js";
pub(crate) const NATIVE_CUSTOM_CSS_PATH: &str = "/static/native-custom-css.v1.js";
pub(crate) const NATIVE_SETTINGS_TRANSFER_PATH: &str = "/static/native-settings-transfer.v1.js";
pub(crate) const NATIVE_MATH_PATH: &str = "/static/native-math.v1.js";
pub(crate) const NATIVE_MATH_WORKER_PATH: &str = "/static/native-math-worker.v1.js";
pub(crate) const UPDATER_SOUND_PATH: &str = "/static/notifications/beep.ogg";

pub(crate) const TEGAKI_SCRIPT_PATH: &str = "/static/tegaki/tegaki-0.9.4.v1.js";
pub(crate) const TEGAKI_STYLE_PATH: &str = "/static/tegaki/tegaki-0.9.4.v1.css";
pub(crate) const TEGAKI_FONT_PATH: &str = "/static/tegaki/tegaki-icons.v1.woff";

const ASSETS: &[(&str, &str, &[u8])] = &[
    (
        "/static/polls.v1.css",
        "text/css; charset=utf-8",
        include_bytes!("../static/polls.v1.css"),
    ),
    (
        NATIVE_BLOTTER_PATH,
        "text/javascript; charset=utf-8",
        include_bytes!("../static/native-blotter.v1.js"),
    ),
    (
        TEGAKI_STYLE_PATH,
        "text/css; charset=utf-8",
        include_bytes!("../static/tegaki/tegaki-0.9.4.v1.css"),
    ),
    (
        TEGAKI_FONT_PATH,
        "font/woff",
        include_bytes!("../static/tegaki/tegaki-icons.v1.woff"),
    ),
    (
        "/static/catalog/spoiler-a1.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-a1.png"),
    ),
    (
        "/static/catalog/spoiler-co1.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-co1.png"),
    ),
    (
        "/static/catalog/spoiler-co2.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-co2.png"),
    ),
    (
        "/static/catalog/spoiler-co3.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-co3.png"),
    ),
    (
        "/static/catalog/spoiler-co4.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-co4.png"),
    ),
    (
        "/static/catalog/spoiler-co5.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-co5.png"),
    ),
    (
        "/static/catalog/spoiler-jp1.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-jp1.png"),
    ),
    (
        "/static/catalog/spoiler-lit1.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-lit1.png"),
    ),
    (
        "/static/catalog/spoiler-m1.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-m1.png"),
    ),
    (
        "/static/catalog/spoiler-m2.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-m2.png"),
    ),
    (
        "/static/catalog/spoiler-m3.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-m3.png"),
    ),
    (
        "/static/catalog/spoiler-m4.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-m4.png"),
    ),
    (
        "/static/catalog/spoiler-mlp1.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-mlp1.png"),
    ),
    (
        "/static/catalog/spoiler-s4s1.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-s4s1.png"),
    ),
    (
        "/static/catalog/spoiler-s4s2.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-s4s2.png"),
    ),
    (
        "/static/catalog/spoiler-s4s3.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-s4s3.png"),
    ),
    (
        "/static/catalog/spoiler-s4s4.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-s4s4.png"),
    ),
    (
        "/static/catalog/spoiler-s4s5.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-s4s5.png"),
    ),
    (
        "/static/catalog/spoiler-s4s6.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-s4s6.png"),
    ),
    (
        "/static/catalog/spoiler-tg1.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-tg1.png"),
    ),
    (
        "/static/catalog/spoiler-tg2.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-tg2.png"),
    ),
    (
        "/static/catalog/spoiler-tv1.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-tv1.png"),
    ),
    (
        "/static/catalog/spoiler-tv2.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-tv2.png"),
    ),
    (
        "/static/catalog/spoiler-tv3.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-tv3.png"),
    ),
    (
        "/static/catalog/spoiler-tv4.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-tv4.png"),
    ),
    (
        "/static/catalog/spoiler-tv5.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-tv5.png"),
    ),
    (
        "/static/catalog/spoiler-v1.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-v1.png"),
    ),
    (
        "/static/catalog/spoiler-vg1.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-vg1.png"),
    ),
    (
        "/static/catalog/spoiler-vmg1.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-vmg1.png"),
    ),
    (
        "/static/catalog/spoiler-vmg2.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-vmg2.png"),
    ),
    (
        "/static/catalog/spoiler-vmg3.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-vmg3.png"),
    ),
    (
        "/static/catalog/spoiler-vp1.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-vp1.png"),
    ),
    (
        "/static/catalog/spoiler-vr1.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-vr1.png"),
    ),
    (
        "/static/catalog/spoiler-vr2.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-vr2.png"),
    ),
    (
        "/static/catalog/spoiler-vrpg1.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-vrpg1.png"),
    ),
    (
        "/static/catalog/spoiler-vrpg2.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-vrpg2.png"),
    ),
    (
        "/static/catalog/spoiler-vrpg3.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-vrpg3.png"),
    ),
    (
        "/static/catalog/spoiler-vst.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-vst.png"),
    ),
    (
        "/static/catalog/spoiler-vst1.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-vst1.png"),
    ),
    (
        "/static/catalog/spoiler-vt1.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-vt1.png"),
    ),
    (
        "/static/catalog/spoiler-vt2.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-vt2.png"),
    ),
    (
        "/static/catalog/spoiler-vt3.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler-vt3.png"),
    ),
    (
        "/static/flags/flags.css",
        "text/css",
        include_bytes!("../static/flags/flags.css"),
    ),
    (
        "/static/flags/flags.8.png",
        "image/png",
        include_bytes!("../static/flags/flags.8.png"),
    ),
    (
        "/static/flags/board-flags.2.png",
        "image/png",
        include_bytes!("../static/flags/board-flags.2.png"),
    ),
    (
        "/static/flags/board-types.css",
        "text/css; charset=utf-8",
        include_bytes!("../static/flags/board-types.css"),
    ),
    (
        "/static/flags/mlp-flags.3.png",
        "image/png",
        include_bytes!("../static/flags/mlp-flags.3.png"),
    ),
    (
        "/static/flags/lgbt-flags.1.png",
        "image/png",
        include_bytes!("../static/flags/lgbt-flags.1.png"),
    ),
    (
        "/static/identity/modicon.gif",
        "image/gif",
        include_bytes!("../static/identity/modicon.gif"),
    ),
    (
        "/static/identity/modicon@2x.gif",
        "image/gif",
        include_bytes!("../static/identity/modicon@2x.gif"),
    ),
    (
        "/static/identity/adminicon.gif",
        "image/gif",
        include_bytes!("../static/identity/adminicon.gif"),
    ),
    (
        "/static/identity/adminicon@2x.gif",
        "image/gif",
        include_bytes!("../static/identity/adminicon@2x.gif"),
    ),
    (
        "/static/identity/managericon.gif",
        "image/gif",
        include_bytes!("../static/identity/managericon.gif"),
    ),
    (
        "/static/identity/managericon@2x.gif",
        "image/gif",
        include_bytes!("../static/identity/managericon@2x.gif"),
    ),
    (
        "/static/identity/developericon.gif",
        "image/gif",
        include_bytes!("../static/identity/developericon.gif"),
    ),
    (
        "/static/identity/developericon@2x.gif",
        "image/gif",
        include_bytes!("../static/identity/developericon@2x.gif"),
    ),
    (
        "/static/identity/foundericon.gif",
        "image/gif",
        include_bytes!("../static/identity/foundericon.gif"),
    ),
    (
        "/static/navigation/futaba/arrow_up.png",
        "image/png",
        include_bytes!("../static/navigation/futaba/arrow_up.png"),
    ),
    (
        "/static/navigation/futaba/arrow_up@2x.png",
        "image/png",
        include_bytes!("../static/navigation/futaba/arrow_up@2x.png"),
    ),
    (
        "/static/navigation/futaba/arrow_down.png",
        "image/png",
        include_bytes!("../static/navigation/futaba/arrow_down.png"),
    ),
    (
        "/static/navigation/futaba/arrow_down@2x.png",
        "image/png",
        include_bytes!("../static/navigation/futaba/arrow_down@2x.png"),
    ),
    (
        "/static/navigation/burichan/arrow_up.png",
        "image/png",
        include_bytes!("../static/navigation/burichan/arrow_up.png"),
    ),
    (
        "/static/navigation/burichan/arrow_up@2x.png",
        "image/png",
        include_bytes!("../static/navigation/burichan/arrow_up@2x.png"),
    ),
    (
        "/static/navigation/burichan/arrow_down.png",
        "image/png",
        include_bytes!("../static/navigation/burichan/arrow_down.png"),
    ),
    (
        "/static/navigation/burichan/arrow_down@2x.png",
        "image/png",
        include_bytes!("../static/navigation/burichan/arrow_down@2x.png"),
    ),
    (
        "/static/navigation/tomorrow/arrow_up.png",
        "image/png",
        include_bytes!("../static/navigation/tomorrow/arrow_up.png"),
    ),
    (
        "/static/navigation/tomorrow/arrow_up@2x.png",
        "image/png",
        include_bytes!("../static/navigation/tomorrow/arrow_up@2x.png"),
    ),
    (
        "/static/navigation/tomorrow/arrow_down.png",
        "image/png",
        include_bytes!("../static/navigation/tomorrow/arrow_down.png"),
    ),
    (
        "/static/navigation/tomorrow/arrow_down@2x.png",
        "image/png",
        include_bytes!("../static/navigation/tomorrow/arrow_down@2x.png"),
    ),
    (
        "/static/navigation/photon/arrow_up.png",
        "image/png",
        include_bytes!("../static/navigation/photon/arrow_up.png"),
    ),
    (
        "/static/navigation/photon/arrow_up@2x.png",
        "image/png",
        include_bytes!("../static/navigation/photon/arrow_up@2x.png"),
    ),
    (
        "/static/navigation/photon/arrow_down.png",
        "image/png",
        include_bytes!("../static/navigation/photon/arrow_down.png"),
    ),
    (
        "/static/navigation/photon/arrow_down@2x.png",
        "image/png",
        include_bytes!("../static/navigation/photon/arrow_down@2x.png"),
    ),
    (
        "/static/derefer.css",
        "text/css; charset=utf-8",
        include_bytes!("../static/derefer.css"),
    ),
    (
        "/static/updating-index.v1.css",
        "text/css; charset=utf-8",
        include_bytes!("../static/updating-index.v1.css"),
    ),
    (
        "/static/catalog/filedeleted-res.gif",
        "image/gif",
        include_bytes!("../static/catalog/filedeleted-res.gif"),
    ),
    (
        "/static/catalog/filedeleted-res@2x.gif",
        "image/gif",
        include_bytes!("../static/catalog/filedeleted-res@2x.gif"),
    ),
    (
        "/static/catalog/nofile.png",
        "image/png",
        include_bytes!("../static/catalog/nofile.png"),
    ),
    (
        "/static/catalog/spoiler.png",
        "image/png",
        include_bytes!("../static/catalog/spoiler.png"),
    ),
    (
        "/static/catalog/sticky.gif",
        "image/gif",
        include_bytes!("../static/catalog/sticky.gif"),
    ),
    (
        "/static/catalog/closed.gif",
        "image/gif",
        include_bytes!("../static/catalog/closed.gif"),
    ),
    (
        "/static/catalog/sticky@2x.gif",
        "image/gif",
        include_bytes!("../static/catalog/sticky@2x.gif"),
    ),
    (
        "/static/catalog/closed@2x.gif",
        "image/gif",
        include_bytes!("../static/catalog/closed@2x.gif"),
    ),
    (
        "/static/catalog/buttonfade-dark.png",
        "image/png",
        include_bytes!("../static/catalog/buttonfade-dark.png"),
    ),
    (
        "/static/watcher/futaba/watch_thread_off.png",
        "image/png",
        include_bytes!("../static/watcher/futaba/watch_thread_off.png"),
    ),
    (
        "/static/watcher/futaba/watch_thread_off@2x.png",
        "image/png",
        include_bytes!("../static/watcher/futaba/watch_thread_off@2x.png"),
    ),
    (
        "/static/watcher/futaba/watch_thread_on.png",
        "image/png",
        include_bytes!("../static/watcher/futaba/watch_thread_on.png"),
    ),
    (
        "/static/watcher/futaba/watch_thread_on@2x.png",
        "image/png",
        include_bytes!("../static/watcher/futaba/watch_thread_on@2x.png"),
    ),
    (
        "/static/watcher/futaba/refresh.png",
        "image/png",
        include_bytes!("../static/watcher/futaba/refresh.png"),
    ),
    (
        "/static/watcher/futaba/refresh@2x.png",
        "image/png",
        include_bytes!("../static/watcher/futaba/refresh@2x.png"),
    ),
    (
        "/static/watcher/futaba/cross.png",
        "image/png",
        include_bytes!("../static/watcher/futaba/cross.png"),
    ),
    (
        "/static/watcher/futaba/cross@2x.png",
        "image/png",
        include_bytes!("../static/watcher/futaba/cross@2x.png"),
    ),
    (
        "/static/watcher/futaba/post_expand_rotate.gif",
        "image/gif",
        include_bytes!("../static/watcher/futaba/post_expand_rotate.gif"),
    ),
    (
        "/static/watcher/futaba/post_expand_rotate@2x.gif",
        "image/gif",
        include_bytes!("../static/watcher/futaba/post_expand_rotate@2x.gif"),
    ),
    (
        "/static/watcher/burichan/watch_thread_off.png",
        "image/png",
        include_bytes!("../static/watcher/burichan/watch_thread_off.png"),
    ),
    (
        "/static/watcher/burichan/watch_thread_off@2x.png",
        "image/png",
        include_bytes!("../static/watcher/burichan/watch_thread_off@2x.png"),
    ),
    (
        "/static/watcher/burichan/watch_thread_on.png",
        "image/png",
        include_bytes!("../static/watcher/burichan/watch_thread_on.png"),
    ),
    (
        "/static/watcher/burichan/watch_thread_on@2x.png",
        "image/png",
        include_bytes!("../static/watcher/burichan/watch_thread_on@2x.png"),
    ),
    (
        "/static/watcher/burichan/refresh.png",
        "image/png",
        include_bytes!("../static/watcher/burichan/refresh.png"),
    ),
    (
        "/static/watcher/burichan/refresh@2x.png",
        "image/png",
        include_bytes!("../static/watcher/burichan/refresh@2x.png"),
    ),
    (
        "/static/watcher/burichan/cross.png",
        "image/png",
        include_bytes!("../static/watcher/burichan/cross.png"),
    ),
    (
        "/static/watcher/burichan/cross@2x.png",
        "image/png",
        include_bytes!("../static/watcher/burichan/cross@2x.png"),
    ),
    (
        "/static/watcher/burichan/post_expand_rotate.gif",
        "image/gif",
        include_bytes!("../static/watcher/burichan/post_expand_rotate.gif"),
    ),
    (
        "/static/watcher/burichan/post_expand_rotate@2x.gif",
        "image/gif",
        include_bytes!("../static/watcher/burichan/post_expand_rotate@2x.gif"),
    ),
    (
        "/static/watcher/tomorrow/watch_thread_off.png",
        "image/png",
        include_bytes!("../static/watcher/tomorrow/watch_thread_off.png"),
    ),
    (
        "/static/watcher/tomorrow/watch_thread_off@2x.png",
        "image/png",
        include_bytes!("../static/watcher/tomorrow/watch_thread_off@2x.png"),
    ),
    (
        "/static/watcher/tomorrow/watch_thread_on.png",
        "image/png",
        include_bytes!("../static/watcher/tomorrow/watch_thread_on.png"),
    ),
    (
        "/static/watcher/tomorrow/watch_thread_on@2x.png",
        "image/png",
        include_bytes!("../static/watcher/tomorrow/watch_thread_on@2x.png"),
    ),
    (
        "/static/watcher/tomorrow/refresh.png",
        "image/png",
        include_bytes!("../static/watcher/tomorrow/refresh.png"),
    ),
    (
        "/static/watcher/tomorrow/refresh@2x.png",
        "image/png",
        include_bytes!("../static/watcher/tomorrow/refresh@2x.png"),
    ),
    (
        "/static/watcher/tomorrow/cross.png",
        "image/png",
        include_bytes!("../static/watcher/tomorrow/cross.png"),
    ),
    (
        "/static/watcher/tomorrow/cross@2x.png",
        "image/png",
        include_bytes!("../static/watcher/tomorrow/cross@2x.png"),
    ),
    (
        "/static/watcher/tomorrow/post_expand_rotate.gif",
        "image/gif",
        include_bytes!("../static/watcher/tomorrow/post_expand_rotate.gif"),
    ),
    (
        "/static/watcher/tomorrow/post_expand_rotate@2x.gif",
        "image/gif",
        include_bytes!("../static/watcher/tomorrow/post_expand_rotate@2x.gif"),
    ),
    (
        "/static/watcher/photon/watch_thread_off.png",
        "image/png",
        include_bytes!("../static/watcher/photon/watch_thread_off.png"),
    ),
    (
        "/static/watcher/photon/watch_thread_off@2x.png",
        "image/png",
        include_bytes!("../static/watcher/photon/watch_thread_off@2x.png"),
    ),
    (
        "/static/watcher/photon/watch_thread_on.png",
        "image/png",
        include_bytes!("../static/watcher/photon/watch_thread_on.png"),
    ),
    (
        "/static/watcher/photon/watch_thread_on@2x.png",
        "image/png",
        include_bytes!("../static/watcher/photon/watch_thread_on@2x.png"),
    ),
    (
        "/static/watcher/photon/refresh.png",
        "image/png",
        include_bytes!("../static/watcher/photon/refresh.png"),
    ),
    (
        "/static/watcher/photon/refresh@2x.png",
        "image/png",
        include_bytes!("../static/watcher/photon/refresh@2x.png"),
    ),
    (
        "/static/watcher/photon/cross.png",
        "image/png",
        include_bytes!("../static/watcher/photon/cross.png"),
    ),
    (
        "/static/watcher/photon/cross@2x.png",
        "image/png",
        include_bytes!("../static/watcher/photon/cross@2x.png"),
    ),
    (
        "/static/watcher/photon/post_expand_rotate.gif",
        "image/gif",
        include_bytes!("../static/watcher/photon/post_expand_rotate.gif"),
    ),
    (
        "/static/watcher/photon/post_expand_rotate@2x.gif",
        "image/gif",
        include_bytes!("../static/watcher/photon/post_expand_rotate@2x.gif"),
    ),
    (
        "/static/watcher/buttonfade-blue.png",
        "image/png",
        include_bytes!("../static/watcher/buttonfade-blue.png"),
    ),
    (
        "/static/watcher/buttonfade.png",
        "image/png",
        include_bytes!("../static/watcher/buttonfade.png"),
    ),
    (
        "/static/watcher/futaba/post_expand_minus.png",
        "image/png",
        include_bytes!("../static/watcher/futaba/post_expand_minus.png"),
    ),
    (
        "/static/watcher/futaba/post_expand_minus@2x.png",
        "image/png",
        include_bytes!("../static/watcher/futaba/post_expand_minus@2x.png"),
    ),
    (
        "/static/watcher/futaba/post_expand_plus.png",
        "image/png",
        include_bytes!("../static/watcher/futaba/post_expand_plus.png"),
    ),
    (
        "/static/watcher/futaba/post_expand_plus@2x.png",
        "image/png",
        include_bytes!("../static/watcher/futaba/post_expand_plus@2x.png"),
    ),
    (
        "/static/watcher/burichan/post_expand_minus.png",
        "image/png",
        include_bytes!("../static/watcher/burichan/post_expand_minus.png"),
    ),
    (
        "/static/watcher/burichan/post_expand_minus@2x.png",
        "image/png",
        include_bytes!("../static/watcher/burichan/post_expand_minus@2x.png"),
    ),
    (
        "/static/watcher/burichan/post_expand_plus.png",
        "image/png",
        include_bytes!("../static/watcher/burichan/post_expand_plus.png"),
    ),
    (
        "/static/watcher/burichan/post_expand_plus@2x.png",
        "image/png",
        include_bytes!("../static/watcher/burichan/post_expand_plus@2x.png"),
    ),
    (
        "/static/watcher/tomorrow/post_expand_minus.png",
        "image/png",
        include_bytes!("../static/watcher/tomorrow/post_expand_minus.png"),
    ),
    (
        "/static/watcher/tomorrow/post_expand_minus@2x.png",
        "image/png",
        include_bytes!("../static/watcher/tomorrow/post_expand_minus@2x.png"),
    ),
    (
        "/static/watcher/tomorrow/post_expand_plus.png",
        "image/png",
        include_bytes!("../static/watcher/tomorrow/post_expand_plus.png"),
    ),
    (
        "/static/watcher/tomorrow/post_expand_plus@2x.png",
        "image/png",
        include_bytes!("../static/watcher/tomorrow/post_expand_plus@2x.png"),
    ),
    (
        "/static/watcher/photon/post_expand_minus.png",
        "image/png",
        include_bytes!("../static/watcher/photon/post_expand_minus.png"),
    ),
    (
        "/static/watcher/photon/post_expand_minus@2x.png",
        "image/png",
        include_bytes!("../static/watcher/photon/post_expand_minus@2x.png"),
    ),
    (
        "/static/watcher/photon/post_expand_plus.png",
        "image/png",
        include_bytes!("../static/watcher/photon/post_expand_plus.png"),
    ),
    (
        "/static/watcher/photon/post_expand_plus@2x.png",
        "image/png",
        include_bytes!("../static/watcher/photon/post_expand_plus@2x.png"),
    ),
    (
        "/static/notifications/favicon.ico",
        "image/x-icon",
        include_bytes!("../static/notifications/favicon.ico"),
    ),
    (
        "/static/notifications/favicon-ws.ico",
        "image/x-icon",
        include_bytes!("../static/notifications/favicon-ws.ico"),
    ),
    (
        "/static/notifications/favicon-ws-newposts.ico",
        "image/x-icon",
        include_bytes!("../static/notifications/favicon-ws-newposts.ico"),
    ),
    (
        "/static/notifications/favicon-ws-newreplies.ico",
        "image/x-icon",
        include_bytes!("../static/notifications/favicon-ws-newreplies.ico"),
    ),
    (
        "/static/notifications/favicon-ws-deadthread.ico",
        "image/x-icon",
        include_bytes!("../static/notifications/favicon-ws-deadthread.ico"),
    ),
    (
        "/static/notifications/favicon-ws-newfilters.ico",
        "image/x-icon",
        include_bytes!("../static/notifications/favicon-ws-newfilters.ico"),
    ),
    (
        "/static/notifications/favicon-nws-newposts.ico",
        "image/x-icon",
        include_bytes!("../static/notifications/favicon-nws-newposts.ico"),
    ),
    (
        "/static/notifications/favicon-nws-newreplies.ico",
        "image/x-icon",
        include_bytes!("../static/notifications/favicon-nws-newreplies.ico"),
    ),
    (
        "/static/notifications/favicon-nws-deadthread.ico",
        "image/x-icon",
        include_bytes!("../static/notifications/favicon-nws-deadthread.ico"),
    ),
    (
        "/static/notifications/favicon-nws-newfilters.ico",
        "image/x-icon",
        include_bytes!("../static/notifications/favicon-nws-newfilters.ico"),
    ),
    (
        "/static/catalog/buttons/futaba/question.png",
        "image/png",
        include_bytes!("../static/catalog/buttons/futaba/question.png"),
    ),
    (
        "/static/catalog/buttons/futaba/question@2x.png",
        "image/png",
        include_bytes!("../static/catalog/buttons/futaba/question@2x.png"),
    ),
    (
        "/static/catalog/buttons/burichan/question.png",
        "image/png",
        include_bytes!("../static/catalog/buttons/burichan/question.png"),
    ),
    (
        "/static/catalog/buttons/burichan/question@2x.png",
        "image/png",
        include_bytes!("../static/catalog/buttons/burichan/question@2x.png"),
    ),
    (
        "/static/catalog/buttons/tomorrow/question.png",
        "image/png",
        include_bytes!("../static/catalog/buttons/tomorrow/question.png"),
    ),
    (
        "/static/catalog/buttons/tomorrow/question@2x.png",
        "image/png",
        include_bytes!("../static/catalog/buttons/tomorrow/question@2x.png"),
    ),
    (
        "/static/catalog/buttons/photon/question.png",
        "image/png",
        include_bytes!("../static/catalog/buttons/photon/question.png"),
    ),
    (
        "/static/catalog/buttons/photon/question@2x.png",
        "image/png",
        include_bytes!("../static/catalog/buttons/photon/question@2x.png"),
    ),
];

pub(crate) fn routes<S: Clone + Send + Sync + 'static>() -> Router<S> {
    let mut router = Router::new().route(
        UPDATER_SOUND_PATH,
        get(|| async {
            (
                [
                    (header::CONTENT_TYPE, "audio/ogg"),
                    (header::CACHE_CONTROL, "public, max-age=0, must-revalidate"),
                ],
                include_bytes!("../static/notifications/beep.ogg").as_slice(),
            )
        }),
    );
    for &(path, mime, bytes) in ASSETS {
        router = router.route(
            path,
            get(move || async move {
                (
                    [
                        (header::CONTENT_TYPE, mime),
                        (header::CACHE_CONTROL, "public, max-age=0, must-revalidate"),
                    ],
                    bytes,
                )
            }),
        );
    }
    for (path, bytes) in [
        (
            TEGAKI_SCRIPT_PATH,
            include_bytes!("../static/tegaki/tegaki-0.9.4.v1.js").as_slice(),
        ),
        (
            NATIVE_MATH_PATH,
            include_bytes!("../static/native-math.v1.js").as_slice(),
        ),
        (
            NATIVE_MATH_WORKER_PATH,
            include_bytes!("../static/native-math-worker.v1.js").as_slice(),
        ),
        (
            REPORT_POPUP_PATH,
            include_bytes!("../static/report-popup.v1.js").as_slice(),
        ),
        (
            CATALOG_FILTER_PATH,
            include_bytes!("../static/catalog-filters.v1.js").as_slice(),
        ),
        (
            CATALOG_FILTER_CORE_PATH,
            include_bytes!("../static/catalog-filter-core.v1.js").as_slice(),
        ),
        (
            CATALOG_THEME_PATH,
            include_bytes!("../static/catalog-theme.v1.js").as_slice(),
        ),
        (
            NATIVE_EMBEDS_PATH,
            include_bytes!("../static/native-embeds.v1.js").as_slice(),
        ),
        (
            NATIVE_CUSTOM_CSS_PATH,
            include_bytes!("../static/native-custom-css.v1.js").as_slice(),
        ),
        (
            NATIVE_SETTINGS_TRANSFER_PATH,
            include_bytes!("../static/native-settings-transfer.v1.js").as_slice(),
        ),
        (
            NATIVE_NAVIGATION_PATH,
            include_bytes!("../static/native-navigation.v1.js").as_slice(),
        ),
        (
            PAGE_CHROME_PATH,
            include_bytes!("../static/page-chrome.v1.js").as_slice(),
        ),
        (
            NATIVE_LAYOUT_PATH,
            include_bytes!("../static/native-layout.v1.js").as_slice(),
        ),
        (
            NATIVE_THREAD_CONTROLS_PATH,
            include_bytes!("../static/native-thread-controls.v1.js").as_slice(),
        ),
        (
            NATIVE_THREAD_STATS_PATH,
            include_bytes!("../static/native-thread-stats.v1.js").as_slice(),
        ),
        (
            NATIVE_DISPLAY_PATH,
            include_bytes!("../static/native-display.v1.js").as_slice(),
        ),
        (
            NATIVE_POST_TOOLTIPS_PATH,
            include_bytes!("../static/native-post-tooltips.v1.js").as_slice(),
        ),
        (
            NATIVE_IMAGES_PATH,
            include_bytes!("../static/native-images.v1.js").as_slice(),
        ),
        (
            NATIVE_POST_DELETION_PATH,
            include_bytes!("../static/native-post-deletion.v1.js").as_slice(),
        ),
        (
            NATIVE_BACKLINKS_PATH,
            include_bytes!("../static/native-backlinks.v1.js").as_slice(),
        ),
        (
            NATIVE_FILTER_PATH,
            include_bytes!("../static/native-filter.v1.js").as_slice(),
        ),
        (
            NATIVE_QUICK_REPLY_PATH,
            include_bytes!("../static/native-quick-reply.v1.js").as_slice(),
        ),
        (
            WATCHER_POSITION_PATH,
            include_bytes!("../static/watcher-position.v1.js").as_slice(),
        ),
        (
            NATIVE_SETTINGS_PATH,
            include_bytes!("../static/native-settings.v1.js").as_slice(),
        ),
        (
            POST_TRACKING_PATH,
            include_bytes!("../static/post-tracking.v1.js").as_slice(),
        ),
        (
            CATALOG_SCRIPT_PATH,
            include_bytes!("../static/catalog-preferences.v1.js").as_slice(),
        ),
        (
            WATCHER_SCRIPT_PATH,
            include_bytes!("../static/thread-watcher.v1.js").as_slice(),
        ),
        (
            WATCHER_CORE_PATH,
            include_bytes!("../static/thread-watcher-core.v1.js").as_slice(),
        ),
    ] {
        router = router.route(
            path,
            get(move || async move {
                (
                    [
                        (header::CONTENT_TYPE, "text/javascript; charset=utf-8"),
                        (header::CACHE_CONTROL, "public, max-age=0, must-revalidate"),
                    ],
                    bytes,
                )
            }),
        );
    }
    router
}

pub(crate) fn image_sources(origin: &str) -> String {
    ASSETS
        .iter()
        .filter(|(_, mime, _)| mime.starts_with("image/"))
        .map(|(path, _, _)| format!("{origin}{path}"))
        .chain([
            format!("{origin}/static/catalog/spoiler-news1.png"),
            format!("{origin}/static/catalog/spoiler-vm1.png"),
        ])
        .collect::<Vec<_>>()
        .join(" ")
}
